name: my-teste-2
on:
  push:
    branches:
      - main
      - master
run-name: Running CI and CD my teste  🚀🚀🚀
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout - clone
      - uses: actions/checkout@v3

      - name: Git Cache 
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'mm.ss'

      - name: Usage Time
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME 

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Compilation
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/teste-aula:${{ steps.time.outputs.time }}

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: main
          valueFile: 'meu-chart/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.time.outputs.time }}
          commitChange: true
          updateFile: true
          message: 'Update Image Tag Version to ${{ steps.time.outputs.time }}-${{ github.sha }}'